version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_URI=postgres://test:test@localhost:5432/test"
    depends_on:
      - db
  db:
    image: library/postgres:12-alpine
    environment:
      - "POSTGRES_PASSWORD=test"
