version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/workdir
    ports:
      - "8000:8000"
    environment:
      - DB_URI=postgresql+asyncpg://test:test@db:5432/test
  db:
    image: library/postgres:10-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
