version: "3.9"

services:
  db:
    env_file:
      - .env
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    env_file:
      - ./.env
    build: .
    command: python -m wallet_service.app
    volumes:
      - .:/workdir
    ports:
      - "8000:8000"
    depends_on:
      - db
